### ISSUE TITLE
Can't seem to build using instructions, returns: /img/resin.img: Is a directory

### ISSUE THREAD

**Issue by qbunt** [resin-io/resin-preload-image-script#15]
Using appropriate environment variables, and running the following line to run the docker container:
```
docker run -it -e API_TOKEN=$API_TOKEN -e APP_ID=$APP_ID -v $PATH_TO_IMAGE:/img/resin.img --privileged resin/resin-preload
```
I don't see a built image come through, the script does return with the following error:

```
/usr/src/app/preload.sh: line 61: /img/resin.img: Is a directory
Waiting for Docker to stop...
```

It's entirely possible that I'm running this incorrectly, but wanted to ensure that it was tracked nonetheless.

**Comment by Page-** [comment]
Hey, so my guess is that your `$PATH_TO_IMAGE` was incorrect and didn't exist, which meant that docker automatically created a directory there and mounted it, rather than mounting an img file, hence the `Is a directory` error

**Comment by qbunt** [comment]
Ah I was setting the output path too, I was finally get it to modify an image, thanks for the response. When I boot off the modified image, Resin is still downloading an image, is that right or is something off in my setup? This is a large image, so it's not out of the question.

**Comment by Page-** [comment]
It's correct - the preloaded image is started initially and then the supervisor will check for updates and download any.  I think preloading is particularly useful when you need to configure the network on initial setup, eg in combination with a project making use of https://github.com/resin-io/resin-wifi-connect/ (or something similar) in order to set up a captive portal to configure the wifi credentials at first boot, when you don't know the details of the wifi network in advance.

Of course there are other uses, but preloading is mainly for the initial provisioning/prior to connection stage - after it's connected to resin it goes back to business as usual

**Comment by qbunt** [comment]
Oh, then we're all good then. We have a similar situation but we can't use a captive portal, instead we wrote something to configure wifi via environment variables. This definitely helps out, we have a lot of cards to set up. Thanks for the quick reply @Page- cheers!

**Comment by Page-** [comment]
No problem, glad to hear it's sorted :)
